namespace _Game.Scripts.GamePlay.Types
{
public enum StatType
{
    Inertia = 8,
    MoveSpeed = 0,
    MaxHealth = 10,
    DamageReflection = 4,
    VisionRadius = 1,
    Regeneration = 7,
    Acceleration = 3,
    PhysicalDamage = 6,
    EatingStrength = 11,
    EatingPenetration = 12,
    EatingTime = 13,
    MaxEndurance = 14,
    EnduranceRecovery = 15,
    SprintMultiplier = 16,
    DamageResistance = 17,
    DashPower = 18,
    ColdResistance = 19,
    HeatResistance = 20,
    MinimalComfortableTemperature = 22,
    MaximumComfortableTemperature = 23,
    AttackRange = 25,
    IgnoreDamageResistance = 26,
    Sensorics = 27,
    Disguise = 28,
    LightingRadius = 29,
    Passability = 30,
    XRay = 31,
    AttackSpeed = 32,
    DisguiseInRest = 33,
    OxygenBreathing = 34,
    HydrogenBreathing = 35,
    Bounciness = 36,
    Friction = 37,
}
}